//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrbiApp.Web.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceAr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceAr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HrbiApp.Web.Resource.ResourceAr", typeof(ResourceAr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to أرقام الإسعاف.
        /// </summary>
        public static string Ambulances
        {
            get
            {
                return ResourceManager.GetString("Ambulances", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to درجات الأطباء.
        /// </summary>
        public static string DoctorPositions
        {
            get
            {
                return ResourceManager.GetString("DoctorPositions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الأطباء.
        /// </summary>
        public static string Doctors
        {
            get
            {
                return ResourceManager.GetString("Doctors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حجوزات المعمل.
        /// </summary>
        public static string LabServiceBookings
        {
            get
            {
                return ResourceManager.GetString("LabServiceBookings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خدمات المعمل.
        /// </summary>
        public static string LabServices
        {
            get
            {
                return ResourceManager.GetString("LabServices", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حجوزات التمريض.
        /// </summary>
        public static string NurseBookings
        {
            get
            {
                return ResourceManager.GetString("NurseBookings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خدمات التمريض.
        /// </summary>
        public static string NurseServices
        {
            get
            {
                return ResourceManager.GetString("NurseServices", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الدفوعات.
        /// </summary>
        public static string Payments
        {
            get
            {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الإعدادات.
        /// </summary>
        public static string Setting
        {
            get
            {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التخصصات.
        /// </summary>
        public static string Specializations
        {
            get
            {
                return ResourceManager.GetString("Specializations", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم.
        /// </summary>
        public static string Dashboard
        {
            get
            {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string Logout
        {
            get
            {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
    /// <summary>
        ///   Looks up a localized string similar to رجوع.
        /// </summary>
        public static string Back
        {
            get
            {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
    /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        public static string Add
        {
            get
            {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Update
        {
            get
            {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to تفعيل.
        /// </summary>
        public static string Activate
        {
            get
            {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to تعطيل.
        /// </summary>
        public static string DeActivate
        {
            get
            {
                return ResourceManager.GetString("DeActivate", resourceCulture);
            }
        }
    /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        public static string Details
        {
            get
            {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
    /// <summary>
        ///   Looks up a localized string similar to الهاتق.
        /// </summary>
        public static string Phone
        {
            get
            {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
    }
}
